Rambo-react/ui-meteors

- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
> feat: add Tabs component

- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
> refactor: delete Tabs

- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
> refactor: delete Tabs component

- src/styles/_typography.scss
fix access to mixins to global
> Proj 15 typography

- package.json
- pnpm-lock.yaml
- Добавил компоненты Radix в проект
> Add radix components

- vite.config.ts
- Добавил alias в vite cfg для пути к папке styles, чтобы вместо ../../styles/ в импортах стилей прописывать лишь @styles/
> alias-for-styles: add alias for styles folder

- src/components/Tabs/Tabs.module.scss
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
- добавил компонент Tabs со стилями и stories для storybook
> Proj 13 tabs: add Tabs component

- src/components/Button/Button.module.scss
- src/components/Button/Button.stories.tsx
в прошлый раз случайно в main залил, обновить ветку dev
> PROJ-11 feat: add button

- package.json
- pnpm-lock.yaml
- src/components/TextArea/TextArea.module.scss
- src/components/TextArea/TextArea.stories.tsx
- src/components/TextArea/TextArea.tsx
- src/components/TextArea/index.tsx
-use radix label 
-add textArea component
> PROJ-14_textArea feat: add textArea component

- src/components/CheckBox/CheckBox.module.scss
- src/components/CheckBox/CheckBox.stories.tsx
- src/components/CheckBox/CheckBox.tsx
- src/components/CheckBox/index.ts
- src/components/index.ts
> PROJ-16 add chebox

- src/components/Pagination/Pagination.module.scss
- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/Select/Select.module.scss
- src/components/Pagination/Select/Select.tsx
- src/components/Pagination/Select/index.ts
- src/components/Pagination/index.ts
> Proj-5: add pagination

- src/components/Button/Button.module.scss
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- добавил для типов кнопки только: a или button
- когда кнопка как ссылка, сделал текст кнопки по центру 
- добавил историю кнопки как ссылки
- добавил радиогруппу для выбора : чем будет являться элемент Button, ссылкой или кнопкой
> Button refactor

- src/components/Alert/Alert.tsx
- src/components/Icon/Icon.tsx
- src/components/Input/Input.tsx
- src/components/Menu/Menu.tsx
- src/components/SelectBox/SelectBox.tsx
- src/components/Sidebar/SidebarMenuItem.tsx
> iconFix fix: replace color prop to fill prop

- src/components/HeaderMobile/HeaderMobile.tsx
- src/components/HeaderMobile/LanguageOption.tsx
- исправил пути к стилям, чтобы в storybook не падала ошибка
> PROJ-4_header-mobile fix: fix styles imports

- src/components/CheckBox/CheckBox.tsx
-сделал checked и onChakedChange обязательными свойствами
> PROJ-16_checkBox fix: make checked, onChakedChange as required props

- src/components/Button/Button.module.scss
- изменил стили, чтобы они не пересекались и поведение было как предполагалось в дизайне.
- при наведении
- активной кнопке
- фокус с клавиатуры
> PROJ-11_Button fix: change styles to suit design

- package.json
- фикс иконки
- подняли версию для публикации
> npmVersionChange chore: update package version to 0.1.4

- src/components/CheckBox/CheckBox.tsx
- поменял label на Label из radix (не выделяет текст при двойном клике)
> PROJ-16_ckeckBox refactor: change label to label from radix

- src/components/Header/Header.module.scss
- добавил бордер снизу
- подрефакторил немного стили, что бы header был 60 px высотой и select нормальной высоты
> PROJ-9_header feat: add border bottom

- src/components/Input/Input.module.scss
- для фокуса сделал outline и пофиксил лишние стили
> Proj 19 input

- src/components/Card/Card.module.scss
- src/components/Card/Card.stories.tsx
- src/components/Card/Card.tsx
- расширил список принимаемых пропсов
> Proj-18_card: expanded props

- src/components/Button/Button.module.scss
- пофиксил: при наведении и активации кнопки работали стили даже если было disabled
> PROJ-11_Button fix: fix styles for hover and active

- src/components/Alert/Alert.module.scss
- src/components/Alert/Alert.stories.tsx
- поменял с position:absolute на fixed
- удалил все margins и padding 
- можно позиционировать как padding так и left,right,top, bottom
> PROJ-20_alerts fix: change styles for position:fixed, delete margins

- src/components/TextArea/TextArea.module.scss
- src/components/TextArea/TextArea.tsx
- удалил disabled свойство
- переделал css для label без добавления класса
- добавил custom id
> PROJ-14_textArea fix: remove disabled prop, add custom id, fix styles for label

- src/components/Input/Input.module.scss
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- смена цвета для label при disabled input
- добавил custom id
> PROJ-19_input fix: change label color with disabled input, add custom id

- src/components/Recaptcha/ReCaptcha.module.scss
изменил размер формы recaptcha для мобильной версии
> PROJ-8_recaptcha fix: fix styles adaptive

- src/components/Button/Button.module.scss
- сделал что бы текст в кнопке не переносился
> PROJ-11_Button feat: add styles text-wrap: nowrap

- src/components/SelectBox/SelectBox.module.scss
- src/components/SelectBox/SelectBox.tsx
- добавил адаптив в selectbox, убрал label если экран <= 360 px
> PROJ-17_select-box feat: add adaptive

- src/components/Header/Header.module.scss
- поменял paddings для мобильной версии
> PROJ-9_header fix: change paddings for mobile

- package.json
- src/components/Alert/Alert.module.scss
- src/components/BurgerMenu/BurgerMenu.module.scss
- src/components/Button/Button.module.scss
- src/components/Card/Card.module.scss
- src/components/CheckBox/CheckBox.module.scss
- src/components/DatePicker/Calendar/Calendar.module.scss
- src/components/DatePicker/Calendar/CalendarDay/CalendarDay.module.scss
- src/components/DatePicker/DatePicker.module.scss
- src/components/Header/Header.module.scss
- src/components/Icons/Icon.module.scss
- src/components/Input/Input.module.scss
- src/components/Modal/Modal.module.scss
- src/components/Pagination/Pagination.module.scss
- src/components/Pagination/Select/Select.module.scss
- src/components/RadioGroup/RadioGroup.module.scss
- src/components/Recaptcha/ReCaptcha.module.scss
- src/components/SelectBox/SelectBox.module.scss
- src/components/Sidebar/Sidebar.module.scss
- src/components/Tabs/Tabs.module.scss
- src/components/TextArea/TextArea.module.scss
- src/components/index.ts
- vite.config.ts
- зменил import на use
- удалил  sprite из сборки
- удалил icon компонент из сборки
> RefactorBranch

- src/components/Alert/Alert.module.scss
- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.tsx
- поменял позицию алерта
- добавил проп onClose для отслеживания, когда алерт будет закрыт
> PROJ-20_alerts

- src/components/Header/Header.module.scss
- src/components/Header/Header.tsx
- добавил обработчики событий для header
- изменил тег для titile с <a> на <span>
> PROJ-9_header feat: add handlers for buttons

- src/components/SelectBox/SelectBox.module.scss
- src/components/SelectBox/SelectBox.tsx
- пофисксил баг с медиа запросом
> PROJ-17_select-box fix: styles for media query

- src/components/SelectBox/SelectBox.module.scss
> PROJ-17_select-box fix: border none for mobile

- src/components/Header/Header.module.scss
- src/components/Header/Header.tsx
- заменил кнопки авторизации на children
- для мобильной версии сделал 425 px
> PROJ-9_header fix: change auth buttons to children

- src/components/SelectBox/SelectBox.module.scss
- src/components/SelectBox/SelectBox.tsx
- className не отрабатывал на SelectRadix.ItemText
- изменил media на 425px
> PROJ-17_select-box fix: add span element for style and change media query to 425px

- src/components/Header/Header.module.scss
- в мобильной и десктопной версиях изменил падинги
> PROJ-9_header fix: fix padding

- src/components/Card/Card.module.scss
- рефактор стилей для карточки
> PROJ-18_card fix: fix styles

- src/components/Input/Input.tsx
- пофиксил логику, если извне придёт className в input
> PROJ-19_input fix: fix className usage

- src/components/SelectBox/SelectBox.module.scss
- удалил рамку для мобильной версии
- удалил паддинг справа
- сделал для десктоп минимальную ширину 163px
- сделал для мобильной версии минимальную ширину 42px
> PROJ-17_select-box fix: fix styles for mobile

- src/components/Modal/Modal.module.scss
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- убрал ширину 
- сделал минимальную ширину 330px
- убрал стили для children 
- добавил параметр className
> PROJ-3_modal fix: styles for modal

- src/components/Recaptcha/ReCaptcha.module.scss
- src/components/Recaptcha/ReCaptcha.stories.tsx
- удалил стили для мобильной версии
- ширина будет задаваться контейнером
> PROJ-8_recaptcha fix: styles for media queries

- src/components/Alert/Alert.module.scss
- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.tsx
> PROJ-20_alerts feat: change styles and props

- src/components/Menu/Menu.module.scss
- src/components/Menu/Menu.stories.ts
- src/components/Menu/Menu.tsx
- добавил свойство callbacks, для замены только функций в массиве элементов
> PROJ-24_menu fix: add callbacks as prop, fix styles

- src/components/Sidebar/Sidebar.tsx
- зименил тип для коллбэков на массив обьектов {имя, колбэк}
- изменил логику установки колбэка на кнопку
> PROJ-10_sidebars fix: change type for CallbackItem

- src/components/Menu/Menu.stories.ts
- src/components/Menu/Menu.tsx
- зименил тип для коллбэков на массив обьектов {имя, колбэк}
- изменил логику установки колбэка на кнопку
> PROJ-24_menu fix: change type for CallbackItem

- src/components/Sidebar/Sidebar.tsx
- поменял свойство disabled в кнопке create на false
> PROJ-10-sidebars fix: change disabled to false in Create button

- src/components/Sidebar/Sidebar.module.scss
- установил отступ справа 60 пикселей
> PROJ-10_sidebars fix: set padding left to 60px

- src/components/Button/Button.module.scss
- добавил смещение для кнопки outlined
> PROJ-11_Button fix: add outline offset to outlined button

- src/components/Card/Card.tsx
-добавил возмождность передавать ref
> PROJ-18_card feat: add ref

- src/components/Modal/Modal.tsx
- добавил параметры в useEffect 
- добавил useCallback
> fixBugWithOnCloseOut fix: useEffect params

- src/components/TextArea/TextArea.tsx
Добавил в onChange типизацию аргументов
>  PROJ-14_textArea fix: add arg event in type Props

- package.json
> npmVersionChange chore: update package version to 0.4.8

- src/components/Icons/CloseOutline.tsx
- пробую фиксить баг с иконкой
(если в браузере менять clipPath вручную, то отображается, возможно нужно генерить идшку каждый раз новую)
> PROJ-28_Icon fix: create uniq Id for clipPath

- src/components/TextArea/TextArea.tsx
Изменил начальное состояние useState для того чтобы при открытии editPost корректно отображался счетчик символов
> PROJ-14_textArea fix: change initial state useState

- src/components/TextArea/TextArea.module.scss
- src/components/TextArea/TextArea.tsx
add dop className to maxLength
> PROJ-14_textAria fix: add dop className to maxLength

- package.json
> NpmVersionChange

- src/components/Input/Input.tsx
Чтобы иметь возможность в label отрисовывать span со звездочкой
> feat: add ability to pass to Input label as jsx

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/Select/Select.tsx
- добавил значение по умолчанию
> PROJ-5_pagination fix: add defaultValue to Select

- src/components/GlobalToast/GlobalToast.stories.tsx
- src/components/GlobalToast/GlobalToast.tsx
> PROJ-74_global-toast fix: changed type of notification

- src/components/GlobalToast/GlobalToast.stories.tsx
- src/components/GlobalToast/GlobalToast.tsx
> PROJ-74_global-toast fix: code review 3 delete index Props

- package.json
update package version to 0.4.22
> npmVersionChange chore: update package version to 0.4.22

- src/components/DatePicker/MaskedInput.tsx
> PROJ-25_datePicker fix: delete ref

- src/components/DatePicker/DatePicker.tsx
- src/components/DatePicker/MaskedInput.tsx
> PROJ-25_datePicker fix: add 'use-client'
